---

- hosts: all
  become: true
  pre_tasks:

  - name: update packages
    tags: always
    apt:
      upgrade: dist
      update_cache: yes

- hosts: all
  become: true
  roles:
    - base

- hosts: web_server
  tags: apache,apache2
  become: true
  roles:
    - web_server

- hosts: db_server
  become: true
  roles:
    - db_server

- hosts: file_server
  become: true
  roles:
    - file_server

- hosts: workstation
  become: true
  roles:
    - workstation
