- name: install unzip
  package:
    name: unzip

- name: install terraform
  unarchive:
    src: "{{ terraform_directory }}"
    dest: /usr/local/bin
    remote_src: yes
    owner: root
    group: root
    mode: 755
