- name: install apache
  apt:
    name: "{{ apache_package_name }}"
    state: latest

- name: install php for apache
  apt:
    name: "{{ php_package_name }}"
    state: latest

- name: copy default page
  copy:
    src: default_page.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 644
